// <auto-generated />
using GitHiredApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GitHiredApi.Migrations
{
    [DbContext(typeof(GitHiredApiDbContext))]
    [Migration("20190204194557_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GitHiredApi.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Headline");

                    b.Property<string>("Industry");

                    b.Property<string>("Title");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Headline = "",
                            Industry = "Technology",
                            Title = "Microsoft",
                            Website = "www.microsoft.com"
                        },
                        new
                        {
                            ID = 2,
                            Headline = "",
                            Industry = "e-commerce marketplace",
                            Title = "Groupon",
                            Website = "www.groupon.com"
                        });
                });

            modelBuilder.Entity("GitHiredApi.Models.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Title");

                    b.Property<string>("WageRange");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 0,
                            Description = "Experience with AngularJS, React, Backbone or other Model-View-Whatever frameworks ",
                            Location = "Seattle,WA",
                            Title = "Junior Web Develoer",
                            WageRange = "4k-5k monthly"
                        },
                        new
                        {
                            ID = 2,
                            CompanyID = 0,
                            Description = "Solid understanding of Object Oriented Programming,Outstanding verbal and written communication skills",
                            Location = "Bellevue,WA",
                            Title = "Front-end Developer",
                            WageRange = "5k monthly"
                        },
                        new
                        {
                            ID = 3,
                            CompanyID = 0,
                            Description = " Solid understanding of Object Oriented Programming",
                            Location = "Kirkland,WA",
                            Title = "Java Developer",
                            WageRange = "8k monthly"
                        },
                        new
                        {
                            ID = 4,
                            CompanyID = 0,
                            Description = " Solid understanding of Object Oriented Programming",
                            Location = "Lynwood,WA",
                            Title = "Junior C# Developer",
                            WageRange = "5k-6k monthly"
                        });
                });

            modelBuilder.Entity("GitHiredApi.Models.RequiredSkills", b =>
                {
                    b.Property<int>("skill");

                    b.Property<int>("JobID");

                    b.HasKey("skill", "JobID");

                    b.HasIndex("JobID");

                    b.ToTable("requiredskills");
                });

            modelBuilder.Entity("GitHiredApi.Models.Job", b =>
                {
                    b.HasOne("GitHiredApi.Models.Company", "company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GitHiredApi.Models.RequiredSkills", b =>
                {
                    b.HasOne("GitHiredApi.Models.Job", "job")
                        .WithMany("requiredskills")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
